export const headerStyles = {
  headerWrapper: "z-10 bg-white h-20 sm:h-44 flex flex-col fixed top-0 w-full",
  topBar: "h-20 sm:h-15 lg:h-18 flex items-center justify-between px-5 sm:px-10",
  logoWrapper: "flex w-[100%] sm:w-[100%] lg:w-[50%] gap-6",
  digikalaLogoStyle:"relative w-[30%] sm:w-[30%] md:[30%] lg:w-[30%]",
  searchWrapper: "relative w-[50%] w-[70%] md:w-[70%] sm:w-[70%]",
  searchInput: "w-full h-10 pl-10 pr-3 outline-none bg-gray-100 rounded-lg",
  searchIcon: "absolute left-3 top-1/2 -translate-y-1/2 text-gray-500",
  topLinks: "flex gap-2 [@media(max-width:700px)]:hidden",
  linkButton: "px-4 py-2 cursor-pointer",
  linkButtonWithIcon: "flex gap-2 px-4 py-2 cursor-pointer rounded-lg border border-gray-200",
  secondBar: "h-12 [@media(max-width:700px)]:hidden border-b border-gray-200 flex justify-between px-7",
  menuWrapper: "w-100 flex transition delay-500 flex-row h-full",
  menuItem: "relative text-nowrap flex-1 flex [@media(max-width:700px)]:hidden items-center gap-1 justify-center px-4 cursor-pointer group",
  menuItemSpan: "absolute bottom-0 left-0 w-full h-[3px] bg-orange-500 scale-x-0 origin-left transition-transform duration-600 group-hover:scale-x-100",
  cityButtonWrapper: "[@media(max-width:600px)]:hidden h-8 bg-orange-100 text-orange-700 cursor-pointer px-4 py-2 rounded-2xl ml-10 my-auto text-sm flex justify-center items-center gap-2",
  cityModalWrapper: "flex flex-col w-115 items-center",
  cityTitleStyle:"border-1 border-gray-200 rounded-full flex justify-center items-center py-2",
  arrowLeftStyle:"text-gray-400 ml-2",
  citySearchWrapper: "flex justify-center items-center w-113.5 h-10 bg-gray-100 rounded-sm gap-2 p-2 mt-3",
  citySearchInput: "w-100 h-10 outline-0",
  clearSearchIcon: "rounded-full cursor-pointer bg-gray-700 text-white",
  frequentCitiesSwiper: "flex w-110 gap-2 h-10 mt-2 justify-start rounded-2xl items-center overflow-x-scroll",
  searchResultsList: "h-[60vh] overflow-y-auto overflow-x-hidden",
  searchResultItem: "flex justify-between w-110 items-center py-4 border-b-1 border-b-gray-300",
  categoryModalOverlay: "fixed inset-0 bg-black/50 flex items-center top-44 justify-center z-50",
  categoryModalList: "w-150 h-[70vh] bg-white overflow-y-auto fixed top-43.5 right-7 flex flex-col",
  categoryItem: "p-3 w-70 bg-gray-100 hover:bg-white cursor-pointer text-sm hover:text-red-600",
  categoryItemSubWrapper: "fixed w-150 h-[69vh] bg-white top-44 right-75 overflow-y-auto text-black",
  categoryItemSubContainer: "p-3 rounded-md flex-col mt-2",
  categorySubTitle: "p-2 my-2 w-1/3 text-xl hover:text-red-600 flex",
  categorySubList: "flex flex-col w-70 mt-2",
  categorySubListItem: "flex p-2 hover:text-red-600 cursor-pointer text-gray-400 text-sm",
};